esphome:
  name: relax

esp8266:
  board: esp01_1m

network:
  enable_ipv6: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  use_address: 192.168.3.25

  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

font: 
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_large
    size: 40
  - file: 'materialdesignicons-webfont.ttf'
    id: font_icons_small
    size: 26
    glyphs:
      - "\U000F091C"  # Wall scocone
      - " "




number:
  - platform: template
    min_value: 3
    max_value: 15
    step: 0.1
    name: "Beer max"
    optimistic: True
    restore_value: True
    id: beer_max

dallas:
  pin: GPIO3

i2c:
  sda: GPIO5
  scl: GPIO4
  frequency: 800kHz



display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    rotation: 180°
    id: ssd1306
    # reset_pin: D0
    address: 0x3C
    lambda: |-
      std::string lamp_icon;
      if (id(cooler).state > id(beer_max).state) {
        it.print(0, 0, id(roboto_large), "Warm");
      } else {
        it.print(0, 0, id(roboto_large), "Cold");
      }
      if (id(sauna_light).state == "off") {
        lamp_icon = "  ";
      } else {
        lamp_icon = "\U000F091C";
      }
      it.printf(0, 64, id(roboto_small), TextAlign::BOTTOM_LEFT, "%.1f °C", id(cooler).state);
      it.printf(128, 64, id(font_icons_small), TextAlign::BOTTOM_RIGHT, (lamp_icon).c_str());

binary_sensor:
  - platform: gpio
    name: "Up"
    pin:
      number: GPIO13
      inverted: true
      mode:
        input: true
        pullup: true
        

  - platform: gpio
    name: "Down"
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Right"
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Push"
    pin:
      number: GPIO14
      inverted: true
      mode:
        input: true
        pullup: true



sensor:
  - platform: dallas
    address: 0xa03c01e076a6f428
    name: "Cooler"
    id: cooler
    on_value:
      component.update: ssd1306

  - platform: dallas
    address: 0x73000002d6663d28
    name: "Closet"
  
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
#      a0:
#        name: ESP IP Address 0
#      a1:
#        name: ESP IP Address 1
#      a2:
#        name: ESP IP Address 2
#      a3:
#        name: ESP IP Address 3
#      a4:
#        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
  - platform: homeassistant
    entity_id: light.sauna 
    id: sauna_light
    internal: true
    on_value:
      component.update: ssd1306


